#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alpari.QualityAssurance.Cnx2Redis.Tests.DataContexts
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QDF")]
	public partial class GetTradeswithEventIDDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public GetTradeswithEventIDDataContext() : 
				base(global::Alpari.QualityAssurance.Cnx2Redis.Tests.Properties.Settings.Default.QDFConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public GetTradeswithEventIDDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GetTradeswithEventIDDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GetTradeswithEventIDDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GetTradeswithEventIDDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetTradeswithEventID")]
		public ISingleResult<GetTradeswithEventIDResult> GetTradeswithEventID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> lasteventidprocessed)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), lasteventidprocessed);
			return ((ISingleResult<GetTradeswithEventIDResult>)(result.ReturnValue));
		}
	}
	
	public partial class GetTradeswithEventIDResult
	{
		
		private int _OrderEventID;
		
		private System.Nullable<System.DateTime> _OriginTimeStamp;
		
		private System.Nullable<int> _FillVolume;
		
		private System.Nullable<double> _Price;
		
		private string _Comment;
		
		private string _ExecID;
		
		private int _Side;
		
		private System.Nullable<char> _OrderTimeTypeID;
		
		private char _OrderPriceTypeID;
		
		private string _TEMnemonic;
		
		public GetTradeswithEventIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderEventID", DbType="Int NOT NULL")]
		public int OrderEventID
		{
			get
			{
				return this._OrderEventID;
			}
			set
			{
				if ((this._OrderEventID != value))
				{
					this._OrderEventID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OriginTimeStamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> OriginTimeStamp
		{
			get
			{
				return this._OriginTimeStamp;
			}
			set
			{
				if ((this._OriginTimeStamp != value))
				{
					this._OriginTimeStamp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FillVolume", DbType="Int")]
		public System.Nullable<int> FillVolume
		{
			get
			{
				return this._FillVolume;
			}
			set
			{
				if ((this._FillVolume != value))
				{
					this._FillVolume = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Float")]
		public System.Nullable<double> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="VarChar(3000)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this._Comment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExecID", DbType="VarChar(255)")]
		public string ExecID
		{
			get
			{
				return this._ExecID;
			}
			set
			{
				if ((this._ExecID != value))
				{
					this._ExecID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Side", DbType="Int NOT NULL")]
		public int Side
		{
			get
			{
				return this._Side;
			}
			set
			{
				if ((this._Side != value))
				{
					this._Side = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderTimeTypeID", DbType="Char(1)")]
		public System.Nullable<char> OrderTimeTypeID
		{
			get
			{
				return this._OrderTimeTypeID;
			}
			set
			{
				if ((this._OrderTimeTypeID != value))
				{
					this._OrderTimeTypeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderPriceTypeID", DbType="Char(1) NOT NULL")]
		public char OrderPriceTypeID
		{
			get
			{
				return this._OrderPriceTypeID;
			}
			set
			{
				if ((this._OrderPriceTypeID != value))
				{
					this._OrderPriceTypeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEMnemonic", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string TEMnemonic
		{
			get
			{
				return this._TEMnemonic;
			}
			set
			{
				if ((this._TEMnemonic != value))
				{
					this._TEMnemonic = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
