// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18444
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Alpari.QualityAssurance.Cnx2Redis.Tests.Specs.SelfTest
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("UKUSQDF-117 [AT] Create a localhost redis instance for testing")]
    [NUnit.Framework.CategoryAttribute("UKUSQDF_117")]
    [NUnit.Framework.CategoryAttribute("localhost")]
    [NUnit.Framework.CategoryAttribute("deal:cnx_deals:TestData\\cnx.csv")]
    public partial class UKUSQDF_117ATCreateALocalhostRedisInstanceForTestingFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "UKUSQDF-117 [AT] Create a localhost redis instance for testing.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-GB"), "UKUSQDF-117 [AT] Create a localhost redis instance for testing", "In order to write reliable test code\r\nAs a QDF Tester\r\nI want to be able to seed " +
                    "a local redis instance with test data", ProgrammingLanguage.CSharp, new string[] {
                        "UKUSQDF_117",
                        "localhost",
                        "deal:cnx_deals:TestData\\cnx.csv"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("write test data to localhost")]
        public virtual void WriteTestDataToLocalhost()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("write test data to localhost", ((string[])(null)));
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("I am running a test on localhost", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "DealSource",
                        "ConvertedStartTime",
                        "ConvertedEndTime"});
            table1.AddRow(new string[] {
                        "cnx-deals",
                        "19/06/2014  17:36:00",
                        "19/06/2014  17:44:59"});
#line 9
 testRunner.And("I have the following search criteria for qdf deals", ((string)(null)), table1, "And ");
#line 12
  testRunner.When("I retrieve the qdf deal data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 13
  testRunner.Then("the count of retrieved deals will be 11", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("write test data to localhost and check with MySql")]
        public virtual void WriteTestDataToLocalhostAndCheckWithMySql()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("write test data to localhost and check with MySql", ((string[])(null)));
#line 15
this.ScenarioSetup(scenarioInfo);
#line 16
 testRunner.Given("I am running a test on localhost", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "DealSource",
                        "ConvertedStartTime",
                        "ConvertedEndTime"});
            table2.AddRow(new string[] {
                        "cnx-deals",
                        "19/06/2014  17:36:00",
                        "19/06/2014  17:44:59"});
#line 17
 testRunner.And("I have the following search criteria for qdf deals", ((string)(null)), table2, "And ");
#line 20
  testRunner.When("I retrieve the qdf deal data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "DealId"});
            table3.AddRow(new string[] {
                        "B201417005FFD00"});
            table3.AddRow(new string[] {
                        "B201417005FFN00"});
            table3.AddRow(new string[] {
                        "B201417005FFR00"});
            table3.AddRow(new string[] {
                        "B201417005FFU00"});
            table3.AddRow(new string[] {
                        "B201417005FFX00"});
            table3.AddRow(new string[] {
                        "B201417005FG000"});
            table3.AddRow(new string[] {
                        "B201417005FG300"});
            table3.AddRow(new string[] {
                        "B201417005FR400"});
            table3.AddRow(new string[] {
                        "B201417005FS100"});
            table3.AddRow(new string[] {
                        "B201417005FS400"});
            table3.AddRow(new string[] {
                        "B201417005FTC00"});
#line 21
  testRunner.And("I query cnx trade by trade id for these trade ids:", ((string)(null)), table3, "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "ExcludedFields"});
            table4.AddRow(new string[] {
                        "OrderId"});
            table4.AddRow(new string[] {
                        "Side"});
#line 34
  testRunner.And("I compare the cnx trade deals with the qdf deal data excluding these fields:", ((string)(null)), table4, "And ");
#line 38
  testRunner.Then("the cnx trade deals should match the qdf deal data exactly", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
