// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18444
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Alpari.QA.CC.MT4Positions2RedisTests.Specs.SelfTest
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("UKUSCC_1222CompareArsPositionsInCcMasterToRedisPositionsInCcUatSlave3")]
    [NUnit.Framework.CategoryAttribute("UKUSCC_1222")]
    [NUnit.Framework.CategoryAttribute("CCDataContextPool")]
    public partial class UKUSCC_1222CompareArsPositionsInCcMasterToRedisPositionsInCcUatSlave3Feature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "UKUSCC_1222CompareArsPositionsInCcMasterToRedisPositionsInCcUatSlave3.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-GB"), "UKUSCC_1222CompareArsPositionsInCcMasterToRedisPositionsInCcUatSlave3", "In order to reconcile Ars Snapshots with Redis Snapshots\r\nAs a CC Tester\r\nI want " +
                    "to Compare Ars positions in cc@master to Redis Positions in cc_uat@slave3", ProgrammingLanguage.CSharp, new string[] {
                        "UKUSCC_1222",
                        "CCDataContextPool"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 7
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Connection1",
                        "Connection2"});
            table1.AddRow(new string[] {
                        "CcMaster",
                        "CcSlave"});
#line 8
 testRunner.Given("I have the following connections to cc:-", ((string)(null)), table1, "Given ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Create 2 connections 2 CC on different connection strings")]
        public virtual void Create2Connections2CCOnDifferentConnectionStrings()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create 2 connections 2 CC on different connection strings", ((string[])(null)));
#line 15
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line 16
 testRunner.Then("the count of cc connections is 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Get sample snapshot data from C1")]
        public virtual void GetSampleSnapshotDataFromC1()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get sample snapshot data from C1", ((string[])(null)));
#line 18
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "server1",
                        "server2",
                        "Database1",
                        "Database2",
                        "Connection1",
                        "Connection2",
                        "section",
                        "book",
                        "symbol",
                        "startTime",
                        "endTime"});
            table2.AddRow(new string[] {
                        "C1",
                        "C1 Red",
                        "cc",
                        "cc_uat",
                        "CcMaster",
                        "CcSlave",
                        "default",
                        "A",
                        "EURUSD",
                        "2014/10/27 12:00:00",
                        "2014/10/27 12:10:00"});
#line 19
 testRunner.When("I get cc redis and cc ars position data across db connections for these sets of s" +
                    "napshot parameters:-", ((string)(null)), table2, "When ");
#line 22
 testRunner.Then("the snapshot comparison list contains 11 results", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Do C1 Comparison")]
        public virtual void DoC1Comparison()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Do C1 Comparison", ((string[])(null)));
#line 24
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "server1",
                        "server2",
                        "Database1",
                        "Database2",
                        "Connection1",
                        "Connection2",
                        "section",
                        "book",
                        "symbol",
                        "startTime",
                        "endTime"});
            table3.AddRow(new string[] {
                        "C1",
                        "C1 Red",
                        "cc",
                        "cc_uat",
                        "CcMaster",
                        "CcSlave",
                        "default",
                        "A",
                        "EURUSD",
                        "2014/10/28 17:00:00",
                        "2014/10/29 09:20:00"});
            table3.AddRow(new string[] {
                        "C1",
                        "C1 Red",
                        "cc",
                        "cc_uat",
                        "CcMaster",
                        "CcSlave",
                        "default",
                        "A",
                        "GBPUSD",
                        "2014/10/28 17:00:00",
                        "2014/10/29 09:20:00"});
            table3.AddRow(new string[] {
                        "C1",
                        "C1 Red",
                        "cc",
                        "cc_uat",
                        "CcMaster",
                        "CcSlave",
                        "default",
                        "A",
                        "GBPJPY",
                        "2014/10/28 17:00:00",
                        "2014/10/29 09:20:00"});
            table3.AddRow(new string[] {
                        "C1",
                        "C1 Red",
                        "cc",
                        "cc_uat",
                        "CcMaster",
                        "CcSlave",
                        "default",
                        "A",
                        "USDCHF",
                        "2014/10/28 17:00:00",
                        "2014/10/29 09:20:00"});
            table3.AddRow(new string[] {
                        "C1",
                        "C1 Red",
                        "cc",
                        "cc_uat",
                        "CcMaster",
                        "CcSlave",
                        "default",
                        "A",
                        "EURCHF",
                        "2014/10/28 17:00:00",
                        "2014/10/29 09:20:00"});
            table3.AddRow(new string[] {
                        "C1",
                        "C1 Red",
                        "cc",
                        "cc_uat",
                        "CcMaster",
                        "CcSlave",
                        "default",
                        "A",
                        "USDJPY",
                        "2014/10/28 17:00:00",
                        "2014/10/29 09:20:00"});
            table3.AddRow(new string[] {
                        "C1",
                        "C1 Red",
                        "cc",
                        "cc_uat",
                        "CcMaster",
                        "CcSlave",
                        "default",
                        "B",
                        "EURUSD",
                        "2014/10/28 17:00:00",
                        "2014/10/29 09:20:00"});
            table3.AddRow(new string[] {
                        "C1",
                        "C1 Red",
                        "cc",
                        "cc_uat",
                        "CcMaster",
                        "CcSlave",
                        "default",
                        "B",
                        "GBPUSD",
                        "2014/10/28 17:00:00",
                        "2014/10/29 09:20:00"});
            table3.AddRow(new string[] {
                        "C1",
                        "C1 Red",
                        "cc",
                        "cc_uat",
                        "CcMaster",
                        "CcSlave",
                        "default",
                        "B",
                        "AUDCAD",
                        "2014/10/28 17:00:00",
                        "2014/10/29 09:20:00"});
            table3.AddRow(new string[] {
                        "C1",
                        "C1 Red",
                        "cc",
                        "cc_uat",
                        "CcMaster",
                        "CcSlave",
                        "default",
                        "B",
                        "CL.X4",
                        "2014/10/28 17:00:00",
                        "2014/10/29 09:20:00"});
            table3.AddRow(new string[] {
                        "C1",
                        "C1 Red",
                        "cc",
                        "cc_uat",
                        "CcMaster",
                        "CcSlave",
                        "default",
                        "B",
                        "XAUUSD",
                        "2014/10/28 17:00:00",
                        "2014/10/29 09:20:00"});
            table3.AddRow(new string[] {
                        "C1",
                        "C1 Red",
                        "cc",
                        "cc_uat",
                        "CcMaster",
                        "CcSlave",
                        "default",
                        "B",
                        "XAGUSD",
                        "2014/10/28 17:00:00",
                        "2014/10/29 09:20:00"});
            table3.AddRow(new string[] {
                        "C1",
                        "C1 Red",
                        "cc",
                        "cc_uat",
                        "CcMaster",
                        "CcSlave",
                        "default",
                        "B",
                        "USDJPY",
                        "2014/10/28 17:00:00",
                        "2014/10/29 09:20:00"});
#line 25
 testRunner.When("I get cc redis and cc ars position data across db connections for these sets of s" +
                    "napshot parameters:-", ((string)(null)), table3, "When ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
