@ClientSideFiltering
Feature: QdfDataRetrieval
	In order to access deal data in Redis QDF
	As a QDF Analyst
	I want a UI to retrieve and filter deal data

# expected results based on data generated by https://stash.corp.alpari.com/projects/GRU/repos/qdf.acceptancetests/browse/qdf.AcceptanceTests/qdf.AcceptanceTests/Specs/SelfTests/RedisConnectionSelfTests.feature
# as at https://stash.corp.alpari.com/projects/GRU/repos/qdf.acceptancetests/commits/0d6c19d790dcb3f057236efbf5c65f5cbbbdf0d7
# June 2nd 2014

Scenario: Filter deals by date
	Given I have the following search criteria for qdf deals
	 | ConvertedStartTime   | ConvertedEndTime     |
	 | 05/05/2014  12:45:42 | 05/05/2014  12:49:51 |
	When I retrieve the qdf deal data
	Then no retrieved deal will have a timestamp outside "05/05/2014  12:45:42" to "05/05/2014  12:49:51"
	And the count of retrieved deals will be 101

Scenario: Filter deals by server
	Given I have the following search criteria for qdf deals
	 | Server    | ConvertedStartTime   | ConvertedEndTime     |
	 | Mt4Micro2 | 05/05/2014  12:45:42 | 05/05/2014  12:49:51 |
	When I retrieve the qdf deal data
	Then all retrieved deals will have be for server "Mt4Micro2"
	And the count of retrieved deals will be 16

Scenario: Filter deals by multiple servers
	Given I have the following search criteria for qdf deals
	 | Server                           | ConvertedStartTime   | ConvertedEndTime     |
	 | Mt4Micro2,Mt4Classic1,Mt4Market1 | 05/05/2014  12:45:42 | 05/05/2014  12:49:51 |
	When I retrieve the qdf deal data
	Then the deals retrieved for each server will have the following counts
	| Server      | Count |
	| Mt4Micro2   | 16    |
	| Mt4Classic1 | 2     |
	| Mt4Market1  | 2     |
	And the count of retrieved deals will be 20

Scenario: Filter deals by symbol
	Given I have the following search criteria for qdf deals
	 | Symbol | ConvertedStartTime   | ConvertedEndTime     |
	 | EURUSD | 05/05/2014  12:45:42 | 05/05/2014  12:49:51 |
	When I retrieve the qdf deal data
	Then all retrieved deals will have be for symbol "EURUSD"
	And the count of retrieved deals will be 32

Scenario: Filter deals by multiple symbols
	Given I have the following search criteria for qdf deals
	 | Symbol               | ConvertedStartTime   | ConvertedEndTime     |
	 | EURUSD,NZDUSD,AUDNZD | 05/05/2014  12:45:42 | 05/05/2014  12:49:51 |
	When I retrieve the qdf deal data
	Then the deals retrieved for each symbol will have the following counts
	| Server | Count |
	| EURUSD | 32    |
	| NZDUSD | 3     |
	| AUDNZD | 1     |
	And the count of retrieved deals will be 36

Scenario: Filter deals by book A
	Given I have the following search criteria for qdf deals
	 | Book | ConvertedStartTime   | ConvertedEndTime     |
	 | A    | 05/05/2014  12:45:42 | 05/05/2014  12:49:51 |
	When I retrieve the qdf deal data
	Then all retrieved deals will have be for book "A"
	And the count of retrieved deals will be 32

Scenario: Filter deals by book B
	Given I have the following search criteria for qdf deals
	 | Book | ConvertedStartTime   | ConvertedEndTime     |
	 | B    | 05/05/2014  12:45:42 | 05/05/2014  12:49:51 |
	When I retrieve the qdf deal data
	Then all retrieved deals will have be for book "B"
	And the count of retrieved deals will be 69

Scenario: Filter deals by book symbol and server
	Given I have the following search criteria for qdf deals
	 | Book | Symbol | Server      | ConvertedStartTime   | ConvertedEndTime     |
	 | B    | EURUSD | Mt4Classic2 | 05/05/2014  12:45:42 | 05/05/2014  12:49:51 |
	When I retrieve the qdf deal data
	Then all retrieved deals will have be for book "B"
	And all retrieved deals will have be for symbol "EURUSD"
	And all retrieved deals will have be for server "Mt4Classic2"
	And the count of retrieved deals will be 4

Scenario: Filter deals by multiple symbols and servers
	Given I have the following search criteria for qdf deals
	 | Symbol               | Server                        | ConvertedStartTime   | ConvertedEndTime     |
	 | EURUSD,GBPUSD,AUDJPY | Currenex,Mt5Pro,Mt4JapaneseC1 | 05/05/2014  12:45:42 | 05/05/2014  12:49:51 |
	When I retrieve the qdf deal data
	Then the deals retrieved for each symbol will have the following counts
	| Server | Count |
	| EURUSD | 15    |
	| GBPUSD | 2     |
	| AUDJPY | 1     |
	Then the deals retrieved for each server will have the following counts
	| Server        | Count |
	| Mt4JapaneseC1 | 12    |
	| Currenex      | 5     |
	| Mt5Pro        | 1     |
	And the count of retrieved deals will be 18